import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'skills',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* UI UX */}
      <head>
        <link 
          rel='icon' 
          href='/icon.ico' 
          sizes='any' 
        />
      </head>

      <body>{children}</body>
    </html>
  )
}