import type { Metadata } from 'next';
import './global.css'; 
import Image from 'next/image';


export const metadata: Metadata = {
  title: 'MainScreen',
  description: 'Generated by create next app',
};
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <link 
          rel='icon' 
          href='images/favicon.ico' 
          sizes='any' 
        />
      </head>

      <body>
        {children}
      </body>
    </html>
  )
}