import type { Metadata } from 'next';
 
import './globals.css'; 


export const metadata: Metadata = {
  title: 'My Next.js Site',
  description: 'Generated by create next app',
};
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      {/* add this */}
      <head>
        <link rel='icon' href='/favicon.ico'/>
      </head>
      
      <body>{children}</body>
    </html>
  );
}